# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 38d3bc0e5dfd55faa2d1b3e9756590fec0e87293f72b551c0aa59c5bc4ad9918070df1f0a4470e7a427239cb1b39b7cfb08f2b4211221a5d801982649c804722

test:
  secret_key_base: 05d829f8555189d465c2c60df64453b7564d235f2c54d84c26de20616065c7b96f4b79ac8dcbf4006ce44af38cca6de9ccb28b0c54fbf12744c756d92680702e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
